[package]
name = "x-color-tool"
version = "0.1.0"
edition = "2021"
authors = ["Lorenzo Panieri"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.1.13", features = ["derive"] }
